### PR TITLE
ValentinaAtehortua SEMANTIC HTML tarea-2

### PR DESCRIPTION
**Pull request by ValentinaAtehortuaZ**

### CODE REVIEW

**Comment by emolinaab** [comment]
@ValentinaAtehortuaZ ,

IMG/img folder should only img
index.html should be in the root
styles.css files should be under css folder

**Review by emolinaab — CHANGES_REQUESTED** [review]
@ValentinaAtehortua , CSS folder should be named using lowercase

**Review by ValentinaAtehortuaZ — COMMENTED** [review]
ready changes

**Comment by emolinaab** [comment]
@ValentinaAtehortuaZ looks like you did not change the folder's name

**Review by emolinaab — APPROVED** [review]
Great work!

**Pull request merged**
