### PR TITLE
Final Project - MoviesApp - Sebastian Martinez 

### PR DESCRIPTION
**Pull request by jhonmartinezG**

### CODE REVIEW

**Comment by emolinaab** [comment]
@jhonmartinezG the scope of the final project was to do a pokedex

**Comment by jhonmartinezG** [comment]
Hey Esteban, 
I think you said in the meeting that we can choose another API to create the project. Nevertheless, in my project, I try to follow the instructions given, I mean, you can see the list of movies and also access the detail of each one.
Regards.

**Comment by emolinaab** [comment]
@jhonmartinezG , yes sorry i got confused with other group.

**Review by emolinaab — APPROVED** [review]
@jhonmartinezG great work!

**Pull request merged**
